/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadora2;

/**
 *
 * @author isaac
 */
public class principal extends javax.swing.JFrame {
    
    String operador = "";
    boolean cambioEstado = false;
    float valor1 = 0, valor2 = 0;
    
    public principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Lresultado = new javax.swing.JLabel();
        Lresultado2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        B1 = new javax.swing.JButton();
        B2 = new javax.swing.JButton();
        B3 = new javax.swing.JButton();
        B4 = new javax.swing.JButton();
        B5 = new javax.swing.JButton();
        B6 = new javax.swing.JButton();
        B7 = new javax.swing.JButton();
        B8 = new javax.swing.JButton();
        B9 = new javax.swing.JButton();
        BCE = new javax.swing.JButton();
        B10 = new javax.swing.JButton();
        BIGUAL = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        sumar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        Lresultado.setBackground(new java.awt.Color(0, 204, 153));
        Lresultado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Lresultado.setForeground(new java.awt.Color(0, 153, 153));
        Lresultado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        Lresultado2.setForeground(new java.awt.Color(0, 0, 0));
        Lresultado2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lresultado, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                    .addComponent(Lresultado2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lresultado2, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Lresultado, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(60, 10, 420, 100);

        jPanel2.setLayout(new java.awt.GridLayout(4, 1));

        B1.setBackground(new java.awt.Color(204, 204, 255));
        B1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        B1.setForeground(new java.awt.Color(0, 0, 0));
        B1.setText("1");
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });
        jPanel2.add(B1);

        B2.setBackground(new java.awt.Color(204, 204, 255));
        B2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        B2.setForeground(new java.awt.Color(0, 0, 0));
        B2.setText("2");
        B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2ActionPerformed(evt);
            }
        });
        jPanel2.add(B2);

        B3.setBackground(new java.awt.Color(204, 204, 255));
        B3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        B3.setForeground(new java.awt.Color(0, 0, 0));
        B3.setText("3");
        B3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B3ActionPerformed(evt);
            }
        });
        jPanel2.add(B3);

        B4.setBackground(new java.awt.Color(204, 204, 255));
        B4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        B4.setForeground(new java.awt.Color(0, 0, 0));
        B4.setText("4");
        B4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B4ActionPerformed(evt);
            }
        });
        jPanel2.add(B4);

        B5.setBackground(new java.awt.Color(204, 204, 255));
        B5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        B5.setForeground(new java.awt.Color(0, 0, 0));
        B5.setText("5");
        B5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5ActionPerformed(evt);
            }
        });
        jPanel2.add(B5);

        B6.setBackground(new java.awt.Color(204, 204, 255));
        B6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        B6.setForeground(new java.awt.Color(0, 0, 0));
        B6.setText("6");
        B6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B6ActionPerformed(evt);
            }
        });
        jPanel2.add(B6);

        B7.setBackground(new java.awt.Color(204, 204, 255));
        B7.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        B7.setForeground(new java.awt.Color(0, 0, 0));
        B7.setText("7");
        B7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B7ActionPerformed(evt);
            }
        });
        jPanel2.add(B7);

        B8.setBackground(new java.awt.Color(204, 204, 255));
        B8.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        B8.setForeground(new java.awt.Color(0, 0, 0));
        B8.setText("8");
        B8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B8ActionPerformed(evt);
            }
        });
        jPanel2.add(B8);

        B9.setBackground(new java.awt.Color(204, 204, 255));
        B9.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        B9.setForeground(new java.awt.Color(0, 0, 0));
        B9.setText("9");
        B9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B9ActionPerformed(evt);
            }
        });
        jPanel2.add(B9);

        BCE.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        BCE.setText("ce");
        BCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCEActionPerformed(evt);
            }
        });
        jPanel2.add(BCE);

        B10.setBackground(new java.awt.Color(204, 204, 255));
        B10.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        B10.setForeground(new java.awt.Color(0, 0, 0));
        B10.setText("0");
        B10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B10ActionPerformed(evt);
            }
        });
        jPanel2.add(B10);

        BIGUAL.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        BIGUAL.setText("=");
        BIGUAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BIGUALActionPerformed(evt);
            }
        });
        jPanel2.add(BIGUAL);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(60, 120, 420, 340);

        jPanel3.setLayout(new java.awt.GridLayout(7, 1));

        sumar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        sumar.setText("+");
        sumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumarActionPerformed(evt);
            }
        });
        jPanel3.add(sumar);

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton2.setText("-");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton3.setText("X");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);

        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton4.setText("/");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4);

        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton5.setText(" √");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5);

        jButton6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton6.setText("x^");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6);

        jButton7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton7.setText("π");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(510, 120, 72, 330);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\isaac\\Downloads\\4f9a3863-0f9e-4a16-a438-1fa8f27a614a.jfif")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 640, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B9ActionPerformed
        Lresultado.setText(Lresultado.getText() + "9");
        AlmacenarValores();
    }//GEN-LAST:event_B9ActionPerformed

    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ActionPerformed
        Lresultado.setText(Lresultado.getText() + "1");
        AlmacenarValores();
    }//GEN-LAST:event_B1ActionPerformed

    private void B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2ActionPerformed
        Lresultado.setText(Lresultado.getText() + "2");
        AlmacenarValores();
    }//GEN-LAST:event_B2ActionPerformed

    private void B3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B3ActionPerformed
        Lresultado.setText(Lresultado.getText() + "3");
        AlmacenarValores();
    }//GEN-LAST:event_B3ActionPerformed

    private void B4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B4ActionPerformed
        Lresultado.setText(Lresultado.getText() + "4");
        AlmacenarValores();
    }//GEN-LAST:event_B4ActionPerformed

    private void B5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5ActionPerformed
        Lresultado.setText(Lresultado.getText() + "5");
        AlmacenarValores();
    }//GEN-LAST:event_B5ActionPerformed

    private void B6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B6ActionPerformed
        Lresultado.setText(Lresultado.getText() + "6");
        AlmacenarValores();
    }//GEN-LAST:event_B6ActionPerformed

    private void B7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B7ActionPerformed
        Lresultado.setText(Lresultado.getText() + "7");
        AlmacenarValores();
    }//GEN-LAST:event_B7ActionPerformed

    private void B8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B8ActionPerformed
        Lresultado.setText(Lresultado.getText() + "8");
        AlmacenarValores();

    }//GEN-LAST:event_B8ActionPerformed

    private void B10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B10ActionPerformed
        Lresultado.setText(Lresultado.getText() + "0");
        AlmacenarValores();
    }//GEN-LAST:event_B10ActionPerformed

    private void BCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCEActionPerformed
        Lresultado.setText("");
        float total = 0;
    }//GEN-LAST:event_BCEActionPerformed

    private void sumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumarActionPerformed
        cambioEstado = true;
        operador = "+";
       
        Lresultado.setText("");
        Lresultado2.setText(String.valueOf(valor1) + " " + operador);
    }//GEN-LAST:event_sumarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        operador = "-";
        cambioEstado = true;
        Lresultado.setText("");
        Lresultado2.setText(String.valueOf(valor1) + " " + operador);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void BIGUALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BIGUALActionPerformed
        float total = 0;
        valor2 = Float.parseFloat(Lresultado.getText());
        switch (operador) {
            case "+": 
              suma sumar = new suma(valor1,valor2);
              total=sumar.sumar();
                break;
            case "-":
                resta restar = new resta(valor1, valor2);
                total = restar.restar();
                break;
            case "*":
                multiplicar multiplicacion = new multiplicar(valor1, valor2);
                total = multiplicacion.multiplicacion();
                break;
            case "/":
                dividir division = new dividir(valor1, valor2);
                total = division.division();
                break;
            case "√":
                raiz raizcuadrada = new raiz(valor2);  
                total =  raizcuadrada.raizcuadrada();
                break;
            case "x^":
                exponente elevar = new exponente(valor1, valor2);
                total=elevar.elevar();
                break;
                case "π":
            
                break;
            default:
                throw new AssertionError();
        }
        Lresultado2.setText(String.valueOf(valor1) + " " + operador + String.valueOf(valor2) + " = ");
        Lresultado.setText(String.valueOf(total));
        valor1 = total;
        valor2 = 0;
    }//GEN-LAST:event_BIGUALActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        operador = "*";
        cambioEstado = true;
        Lresultado.setText("");
        Lresultado2.setText(String.valueOf(valor1) + " " + operador);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        operador = "/";
        cambioEstado = true;
        Lresultado.setText("");
        Lresultado2.setText(String.valueOf(valor1) + " " + operador);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        operador = "√";
        cambioEstado = true;
        Lresultado.setText("");
        Lresultado2.setText(String.valueOf(valor1) + " " + operador);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        operador = "x^";
        cambioEstado = true;
        Lresultado.setText("");
        Lresultado2.setText(String.valueOf(valor1) + " " + operador);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       operador = "π";
       cambioEstado=true;
       Lresultado.setText("3.14159265359");
       Lresultado2.setText(String.valueOf(valor1) + " " + operador);
    }//GEN-LAST:event_jButton7ActionPerformed
    private void AlmacenarValores() {
        if (cambioEstado == false) {
            valor1 = Float.parseFloat(Lresultado.getText());
        } else {
            valor2 = Float.parseFloat(Lresultado.getText());
        }
        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B1;
    private javax.swing.JButton B10;
    private javax.swing.JButton B2;
    private javax.swing.JButton B3;
    private javax.swing.JButton B4;
    private javax.swing.JButton B5;
    private javax.swing.JButton B6;
    private javax.swing.JButton B7;
    private javax.swing.JButton B8;
    private javax.swing.JButton B9;
    private javax.swing.JButton BCE;
    private javax.swing.JButton BIGUAL;
    private javax.swing.JLabel Lresultado;
    private javax.swing.JLabel Lresultado2;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton sumar;
    // End of variables declaration//GEN-END:variables
}
